# Generated by Django 5.1 on 2024-08-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_full_name_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_email',
            field=models.BooleanField(default=False),
        ),
    ]
