# Generated by Django 5.0.7 on 2024-08-04 06:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='title'),
        ),
    ]
