# Generated by Django 5.0.7 on 2024-08-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courseprogress_completed_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='completed_percentage',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_topics',
            field=models.ManyToManyField(to='courses.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='notebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='TopicProgress',
        ),
    ]
