# Generated by Django 5.0.8 on 2024-08-27 11:17

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=70, verbose_name='term')),
                ('definition', ckeditor.fields.RichTextField(verbose_name='definition')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesubject')),
            ],
            options={
                'verbose_name_plural': 'Glossaries',
                'ordering': ['term'],
                'unique_together': {('subject', 'term')},
            },
        ),
    ]
