# Generated by Django 5.0.7 on 2024-08-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courseprogress_completed_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='completed_topics',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='last_completed_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.topic'),
        ),
    ]
