# Generated by Django 5.1 on 2024-08-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_courseprogress_completed_topics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'verbose_name_plural': 'Course progresses'},
        ),
    ]
